interface TrackingDocument {
  Number: string;
  StatusCode: string;
  Status: string;
  DateCreated: string;
  CargoDescriptionString: string | null;
  CheckWeight: string;
  CityRecipient: string;
  CounterpartyRecipientDescription: string | null;
  CounterpartySenderDescription: string | null;
  RecipientAddress: string | null;
  RefCityRecipient: string;
  RefCitySender: string;
  ScheduledDeliveryDate: string | null;
  SenderAddress: string | null;
  ServiceType: string;
  VolumeWeight: string;
  RecipientWarehouseTypeRef: string;
  WarehouseRecipient: string;
  RecipientWarehouseIndex: string;
  WarehouseSender: string;
  SenderWarehouseIndex: string;
  WarehouseRecipientInternetAddressRef: string;
  WarehouseSenderInternetAddressRef: string;
  WarehouseRecipientRef: string;
  RefEW: string;
  PayerType: string;
  PaymentMethod: string;
  OwnerDocumentType: string | null;
  ExpressWaybillPaymentStatus: string | null;
  DocumentWeight: number;
  DocumentCost: number;
  CargoType: string | null;
  CitySender: string;
  WarehouseSenderAddress: string | null;
  ClientBarcode: string;
  AfterpaymentOnGoodsCost: string | null;
  InternationalDeliveryType: string | null;
  LightReturnNumber: string | null;
  PossibilityCreateRedirecting: boolean;
  PossibilityCreateReturn: boolean;
  PossibilityCreateRefusal: boolean;
  PossibilityChangeEW: boolean;
  PossibilityChangeCash2Card: boolean;
  PossibilityChangeDeliveryIntervals: boolean;
  PossibilityTermExtension: boolean;
  PossibilityTrusteeRecipient: boolean;
  TrusteeRecipientPhone: string | null;
  PossibilityLightReturn: boolean;
  PossibilityCreateClaim: boolean;
  SecurePayment: boolean;
  RecipientFullName: string | null;
  RedeliverySum: string | null;
  RedeliveryPayer: string | null;
  LastCreatedOnTheBasisPayerType: string | null;
  LastTransactionDateTimeGM: string | null;
  AnnouncedPrice: string | null;
  RedeliveryPaymentCardRef: string | null;
  RedeliveryPaymentCardDescription: string | null;
  CreatedOnTheBasis: string | null;
  ExpressWaybillAmountToPay: string | null;
}
